// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceCommunicate.proto

package com.raycom.comm.proto.service;

public final class ServiceCommunicate {
  private ServiceCommunicate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServiceCommunicateMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 version = 1 [default = 2];
    /**
     * <code>optional int32 version = 1 [default = 2];</code>
     *
     * <pre>
     * 协议版本
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 1 [default = 2];</code>
     *
     * <pre>
     * 协议版本
     * </pre>
     */
    int getVersion();

    // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    boolean hasMessageType();
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType getMessageType();

    // optional bytes businessID = 3;
    /**
     * <code>optional bytes businessID = 3;</code>
     *
     * <pre>
     * 业务ID，唯一
     * </pre>
     */
    boolean hasBusinessID();
    /**
     * <code>optional bytes businessID = 3;</code>
     *
     * <pre>
     * 业务ID，唯一
     * </pre>
     */
    com.google.protobuf.ByteString getBusinessID();

    // optional int32 messageID = 4;
    /**
     * <code>optional int32 messageID = 4;</code>
     *
     * <pre>
     * 消息ID，同一businessID内唯一
     * </pre>
     */
    boolean hasMessageID();
    /**
     * <code>optional int32 messageID = 4;</code>
     *
     * <pre>
     * 消息ID，同一businessID内唯一
     * </pre>
     */
    int getMessageID();

    // optional string name = 5;
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * 发送者名字
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * 发送者名字
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * 发送者名字
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional bytes content = 6;
    /**
     * <code>optional bytes content = 6;</code>
     *
     * <pre>
     * 协议内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 6;</code>
     *
     * <pre>
     * 协议内容
     * </pre>
     */
    com.google.protobuf.ByteString getContent();

    // optional string responseAddress = 7;
    /**
     * <code>optional string responseAddress = 7;</code>
     *
     * <pre>
     * 回复地址，仅在REQUEST中包含
     * </pre>
     */
    boolean hasResponseAddress();
    /**
     * <code>optional string responseAddress = 7;</code>
     *
     * <pre>
     * 回复地址，仅在REQUEST中包含
     * </pre>
     */
    java.lang.String getResponseAddress();
    /**
     * <code>optional string responseAddress = 7;</code>
     *
     * <pre>
     * 回复地址，仅在REQUEST中包含
     * </pre>
     */
    com.google.protobuf.ByteString
        getResponseAddressBytes();

    // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
     *
     * <pre>
     * 回复结果，仅在RESPONSE中包含
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
     *
     * <pre>
     * 回复结果，仅在RESPONSE中包含
     * </pre>
     */
    com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result getResult();
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
     *
     * <pre>
     * 回复结果，仅在RESPONSE中包含
     * </pre>
     */
    com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.ResultOrBuilder getResultOrBuilder();
  }
  /**
   * Protobuf type {@code com.raycom.comm.proto.service.ServiceCommunicateMsg}
   */
  public static final class ServiceCommunicateMsg extends
      com.google.protobuf.GeneratedMessage
      implements ServiceCommunicateMsgOrBuilder {
    // Use ServiceCommunicateMsg.newBuilder() to construct.
    private ServiceCommunicateMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServiceCommunicateMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServiceCommunicateMsg defaultInstance;
    public static ServiceCommunicateMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ServiceCommunicateMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceCommunicateMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType value = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                messageType_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              businessID_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              messageID_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              name_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              content_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              responseAddress_ = input.readBytes();
              break;
            }
            case 66: {
              com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.class, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ServiceCommunicateMsg> PARSER =
        new com.google.protobuf.AbstractParser<ServiceCommunicateMsg>() {
      public ServiceCommunicateMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceCommunicateMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceCommunicateMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQUEST = 0;</code>
       *
       * <pre>
       * 业务申请
       * </pre>
       */
      REQUEST(0, 0),
      /**
       * <code>RESPONSE = 1;</code>
       *
       * <pre>
       * 业务回复
       * </pre>
       */
      RESPONSE(1, 1),
      /**
       * <code>SUBMIT_REQUEST = 2;</code>
       *
       * <pre>
       * 业务预提交申请
       * </pre>
       */
      SUBMIT_REQUEST(2, 2),
      /**
       * <code>SUBMIT_RESPONSE = 3;</code>
       *
       * <pre>
       * 业务预提交回复
       * </pre>
       */
      SUBMIT_RESPONSE(3, 3),
      /**
       * <code>CONFIRM_REQUEST = 4;</code>
       *
       * <pre>
       * 业务确认提交申请
       * </pre>
       */
      CONFIRM_REQUEST(4, 4),
      /**
       * <code>CONFIRM_RESPONSE = 5;</code>
       *
       * <pre>
       * 业务确认提交回复
       * </pre>
       */
      CONFIRM_RESPONSE(5, 5),
      /**
       * <code>CANCEL_REQUEST = 6;</code>
       *
       * <pre>
       * 业务取消提交申请
       * </pre>
       */
      CANCEL_REQUEST(6, 6),
      /**
       * <code>CANCEL_RESPONSE = 7;</code>
       *
       * <pre>
       * 业务取消提交回复
       * </pre>
       */
      CANCEL_RESPONSE(7, 7),
      /**
       * <code>NOTIFICATION = 8;</code>
       *
       * <pre>
       * 通知业务,无须回复
       * </pre>
       */
      NOTIFICATION(8, 8),
      ;

      /**
       * <code>REQUEST = 0;</code>
       *
       * <pre>
       * 业务申请
       * </pre>
       */
      public static final int REQUEST_VALUE = 0;
      /**
       * <code>RESPONSE = 1;</code>
       *
       * <pre>
       * 业务回复
       * </pre>
       */
      public static final int RESPONSE_VALUE = 1;
      /**
       * <code>SUBMIT_REQUEST = 2;</code>
       *
       * <pre>
       * 业务预提交申请
       * </pre>
       */
      public static final int SUBMIT_REQUEST_VALUE = 2;
      /**
       * <code>SUBMIT_RESPONSE = 3;</code>
       *
       * <pre>
       * 业务预提交回复
       * </pre>
       */
      public static final int SUBMIT_RESPONSE_VALUE = 3;
      /**
       * <code>CONFIRM_REQUEST = 4;</code>
       *
       * <pre>
       * 业务确认提交申请
       * </pre>
       */
      public static final int CONFIRM_REQUEST_VALUE = 4;
      /**
       * <code>CONFIRM_RESPONSE = 5;</code>
       *
       * <pre>
       * 业务确认提交回复
       * </pre>
       */
      public static final int CONFIRM_RESPONSE_VALUE = 5;
      /**
       * <code>CANCEL_REQUEST = 6;</code>
       *
       * <pre>
       * 业务取消提交申请
       * </pre>
       */
      public static final int CANCEL_REQUEST_VALUE = 6;
      /**
       * <code>CANCEL_RESPONSE = 7;</code>
       *
       * <pre>
       * 业务取消提交回复
       * </pre>
       */
      public static final int CANCEL_RESPONSE_VALUE = 7;
      /**
       * <code>NOTIFICATION = 8;</code>
       *
       * <pre>
       * 通知业务,无须回复
       * </pre>
       */
      public static final int NOTIFICATION_VALUE = 8;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          case 2: return SUBMIT_REQUEST;
          case 3: return SUBMIT_RESPONSE;
          case 4: return CONFIRM_REQUEST;
          case 5: return CONFIRM_RESPONSE;
          case 6: return CANCEL_REQUEST;
          case 7: return CANCEL_RESPONSE;
          case 8: return NOTIFICATION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType)
    }

    public interface ResultOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;</code>
       *
       * <pre>
       * 结果码
       * </pre>
       */
      boolean hasResultCode();
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;</code>
       *
       * <pre>
       * 结果码
       * </pre>
       */
      com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode getResultCode();

      // optional string errorComment = 2;
      /**
       * <code>optional string errorComment = 2;</code>
       *
       * <pre>
       * 错误说明，仅在resultCode != SUCCESS里包含     
       * </pre>
       */
      boolean hasErrorComment();
      /**
       * <code>optional string errorComment = 2;</code>
       *
       * <pre>
       * 错误说明，仅在resultCode != SUCCESS里包含     
       * </pre>
       */
      java.lang.String getErrorComment();
      /**
       * <code>optional string errorComment = 2;</code>
       *
       * <pre>
       * 错误说明，仅在resultCode != SUCCESS里包含     
       * </pre>
       */
      com.google.protobuf.ByteString
          getErrorCommentBytes();
    }
    /**
     * Protobuf type {@code com.raycom.comm.proto.service.ServiceCommunicateMsg.Result}
     */
    public static final class Result extends
        com.google.protobuf.GeneratedMessage
        implements ResultOrBuilder {
      // Use Result.newBuilder() to construct.
      private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Result defaultInstance;
      public static Result getDefaultInstance() {
        return defaultInstance;
      }

      public Result getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Result(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode value = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  resultCode_ = value;
                }
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                errorComment_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.class, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.Builder.class);
      }

      public static com.google.protobuf.Parser<Result> PARSER =
          new com.google.protobuf.AbstractParser<Result>() {
        public Result parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Result> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode}
       */
      public enum ResultCode
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>SUCCESS = 0;</code>
         *
         * <pre>
         * 成功
         * </pre>
         */
        SUCCESS(0, 0),
        /**
         * <code>FAIL = 1;</code>
         *
         * <pre>
         * 失败
         * </pre>
         */
        FAIL(1, 1),
        /**
         * <code>SYSTEM_INNER_ERROR = 2;</code>
         *
         * <pre>
         * 系统内部错误
         * </pre>
         */
        SYSTEM_INNER_ERROR(2, 2),
        ;

        /**
         * <code>SUCCESS = 0;</code>
         *
         * <pre>
         * 成功
         * </pre>
         */
        public static final int SUCCESS_VALUE = 0;
        /**
         * <code>FAIL = 1;</code>
         *
         * <pre>
         * 失败
         * </pre>
         */
        public static final int FAIL_VALUE = 1;
        /**
         * <code>SYSTEM_INNER_ERROR = 2;</code>
         *
         * <pre>
         * 系统内部错误
         * </pre>
         */
        public static final int SYSTEM_INNER_ERROR_VALUE = 2;


        public final int getNumber() { return value; }

        public static ResultCode valueOf(int value) {
          switch (value) {
            case 0: return SUCCESS;
            case 1: return FAIL;
            case 2: return SYSTEM_INNER_ERROR;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
                public ResultCode findValueByNumber(int number) {
                  return ResultCode.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.getDescriptor().getEnumTypes().get(0);
        }

        private static final ResultCode[] VALUES = values();

        public static ResultCode valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private ResultCode(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode)
      }

      private int bitField0_;
      // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;
      public static final int RESULTCODE_FIELD_NUMBER = 1;
      private com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode resultCode_;
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;</code>
       *
       * <pre>
       * 结果码
       * </pre>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;</code>
       *
       * <pre>
       * 结果码
       * </pre>
       */
      public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode getResultCode() {
        return resultCode_;
      }

      // optional string errorComment = 2;
      public static final int ERRORCOMMENT_FIELD_NUMBER = 2;
      private java.lang.Object errorComment_;
      /**
       * <code>optional string errorComment = 2;</code>
       *
       * <pre>
       * 错误说明，仅在resultCode != SUCCESS里包含     
       * </pre>
       */
      public boolean hasErrorComment() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string errorComment = 2;</code>
       *
       * <pre>
       * 错误说明，仅在resultCode != SUCCESS里包含     
       * </pre>
       */
      public java.lang.String getErrorComment() {
        java.lang.Object ref = errorComment_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorComment_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string errorComment = 2;</code>
       *
       * <pre>
       * 错误说明，仅在resultCode != SUCCESS里包含     
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorCommentBytes() {
        java.lang.Object ref = errorComment_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorComment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        resultCode_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode.SUCCESS;
        errorComment_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, resultCode_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getErrorCommentBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, resultCode_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getErrorCommentBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.raycom.comm.proto.service.ServiceCommunicateMsg.Result}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.ResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.class, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.Builder.class);
        }

        // Construct using com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          resultCode_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode.SUCCESS;
          bitField0_ = (bitField0_ & ~0x00000001);
          errorComment_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_descriptor;
        }

        public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result getDefaultInstanceForType() {
          return com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.getDefaultInstance();
        }

        public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result build() {
          com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result buildPartial() {
          com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result result = new com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.resultCode_ = resultCode_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.errorComment_ = errorComment_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result) {
            return mergeFrom((com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result other) {
          if (other == com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.getDefaultInstance()) return this;
          if (other.hasResultCode()) {
            setResultCode(other.getResultCode());
          }
          if (other.hasErrorComment()) {
            bitField0_ |= 0x00000002;
            errorComment_ = other.errorComment_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;
        private com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode resultCode_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode.SUCCESS;
        /**
         * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;</code>
         *
         * <pre>
         * 结果码
         * </pre>
         */
        public boolean hasResultCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;</code>
         *
         * <pre>
         * 结果码
         * </pre>
         */
        public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode getResultCode() {
          return resultCode_;
        }
        /**
         * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;</code>
         *
         * <pre>
         * 结果码
         * </pre>
         */
        public Builder setResultCode(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          resultCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result.ResultCode resultCode = 1;</code>
         *
         * <pre>
         * 结果码
         * </pre>
         */
        public Builder clearResultCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          resultCode_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.ResultCode.SUCCESS;
          onChanged();
          return this;
        }

        // optional string errorComment = 2;
        private java.lang.Object errorComment_ = "";
        /**
         * <code>optional string errorComment = 2;</code>
         *
         * <pre>
         * 错误说明，仅在resultCode != SUCCESS里包含     
         * </pre>
         */
        public boolean hasErrorComment() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string errorComment = 2;</code>
         *
         * <pre>
         * 错误说明，仅在resultCode != SUCCESS里包含     
         * </pre>
         */
        public java.lang.String getErrorComment() {
          java.lang.Object ref = errorComment_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            errorComment_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string errorComment = 2;</code>
         *
         * <pre>
         * 错误说明，仅在resultCode != SUCCESS里包含     
         * </pre>
         */
        public com.google.protobuf.ByteString
            getErrorCommentBytes() {
          java.lang.Object ref = errorComment_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            errorComment_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string errorComment = 2;</code>
         *
         * <pre>
         * 错误说明，仅在resultCode != SUCCESS里包含     
         * </pre>
         */
        public Builder setErrorComment(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          errorComment_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string errorComment = 2;</code>
         *
         * <pre>
         * 错误说明，仅在resultCode != SUCCESS里包含     
         * </pre>
         */
        public Builder clearErrorComment() {
          bitField0_ = (bitField0_ & ~0x00000002);
          errorComment_ = getDefaultInstance().getErrorComment();
          onChanged();
          return this;
        }
        /**
         * <code>optional string errorComment = 2;</code>
         *
         * <pre>
         * 错误说明，仅在resultCode != SUCCESS里包含     
         * </pre>
         */
        public Builder setErrorCommentBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          errorComment_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.raycom.comm.proto.service.ServiceCommunicateMsg.Result)
      }

      static {
        defaultInstance = new Result(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.raycom.comm.proto.service.ServiceCommunicateMsg.Result)
    }

    private int bitField0_;
    // optional int32 version = 1 [default = 2];
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>optional int32 version = 1 [default = 2];</code>
     *
     * <pre>
     * 协议版本
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 version = 1 [default = 2];</code>
     *
     * <pre>
     * 协议版本
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;
    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType messageType_;
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType getMessageType() {
      return messageType_;
    }

    // optional bytes businessID = 3;
    public static final int BUSINESSID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString businessID_;
    /**
     * <code>optional bytes businessID = 3;</code>
     *
     * <pre>
     * 业务ID，唯一
     * </pre>
     */
    public boolean hasBusinessID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes businessID = 3;</code>
     *
     * <pre>
     * 业务ID，唯一
     * </pre>
     */
    public com.google.protobuf.ByteString getBusinessID() {
      return businessID_;
    }

    // optional int32 messageID = 4;
    public static final int MESSAGEID_FIELD_NUMBER = 4;
    private int messageID_;
    /**
     * <code>optional int32 messageID = 4;</code>
     *
     * <pre>
     * 消息ID，同一businessID内唯一
     * </pre>
     */
    public boolean hasMessageID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 messageID = 4;</code>
     *
     * <pre>
     * 消息ID，同一businessID内唯一
     * </pre>
     */
    public int getMessageID() {
      return messageID_;
    }

    // optional string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * 发送者名字
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * 发送者名字
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * 发送者名字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes content = 6;
    public static final int CONTENT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 6;</code>
     *
     * <pre>
     * 协议内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes content = 6;</code>
     *
     * <pre>
     * 协议内容
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    // optional string responseAddress = 7;
    public static final int RESPONSEADDRESS_FIELD_NUMBER = 7;
    private java.lang.Object responseAddress_;
    /**
     * <code>optional string responseAddress = 7;</code>
     *
     * <pre>
     * 回复地址，仅在REQUEST中包含
     * </pre>
     */
    public boolean hasResponseAddress() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string responseAddress = 7;</code>
     *
     * <pre>
     * 回复地址，仅在REQUEST中包含
     * </pre>
     */
    public java.lang.String getResponseAddress() {
      java.lang.Object ref = responseAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          responseAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string responseAddress = 7;</code>
     *
     * <pre>
     * 回复地址，仅在REQUEST中包含
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResponseAddressBytes() {
      java.lang.Object ref = responseAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;
    public static final int RESULT_FIELD_NUMBER = 8;
    private com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result result_;
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
     *
     * <pre>
     * 回复结果，仅在RESPONSE中包含
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
     *
     * <pre>
     * 回复结果，仅在RESPONSE中包含
     * </pre>
     */
    public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result getResult() {
      return result_;
    }
    /**
     * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
     *
     * <pre>
     * 回复结果，仅在RESPONSE中包含
     * </pre>
     */
    public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.ResultOrBuilder getResultOrBuilder() {
      return result_;
    }

    private void initFields() {
      version_ = 2;
      messageType_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType.REQUEST;
      businessID_ = com.google.protobuf.ByteString.EMPTY;
      messageID_ = 0;
      name_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
      responseAddress_ = "";
      result_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, businessID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, messageID_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, content_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getResponseAddressBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, businessID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, messageID_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, content_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getResponseAddressBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.raycom.comm.proto.service.ServiceCommunicateMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.class, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Builder.class);
      }

      // Construct using com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 2;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000002);
        businessID_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        messageID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        responseAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        if (resultBuilder_ == null) {
          result_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.raycom.comm.proto.service.ServiceCommunicate.internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_descriptor;
      }

      public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg getDefaultInstanceForType() {
        return com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.getDefaultInstance();
      }

      public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg build() {
        com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg buildPartial() {
        com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg result = new com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.businessID_ = businessID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.messageID_ = messageID_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.responseAddress_ = responseAddress_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg) {
          return mergeFrom((com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg other) {
        if (other == com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasBusinessID()) {
          setBusinessID(other.getBusinessID());
        }
        if (other.hasMessageID()) {
          setMessageID(other.getMessageID());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000010;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasResponseAddress()) {
          bitField0_ |= 0x00000040;
          responseAddress_ = other.responseAddress_;
          onChanged();
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 version = 1 [default = 2];
      private int version_ = 2;
      /**
       * <code>optional int32 version = 1 [default = 2];</code>
       *
       * <pre>
       * 协议版本
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 version = 1 [default = 2];</code>
       *
       * <pre>
       * 协议版本
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 1 [default = 2];</code>
       *
       * <pre>
       * 协议版本
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 1 [default = 2];</code>
       *
       * <pre>
       * 协议版本
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 2;
        onChanged();
        return this;
      }

      // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;
      private com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType messageType_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType.REQUEST;
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public Builder setMessageType(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.MessageType messageType = 2;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.MessageType.REQUEST;
        onChanged();
        return this;
      }

      // optional bytes businessID = 3;
      private com.google.protobuf.ByteString businessID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes businessID = 3;</code>
       *
       * <pre>
       * 业务ID，唯一
       * </pre>
       */
      public boolean hasBusinessID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes businessID = 3;</code>
       *
       * <pre>
       * 业务ID，唯一
       * </pre>
       */
      public com.google.protobuf.ByteString getBusinessID() {
        return businessID_;
      }
      /**
       * <code>optional bytes businessID = 3;</code>
       *
       * <pre>
       * 业务ID，唯一
       * </pre>
       */
      public Builder setBusinessID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        businessID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes businessID = 3;</code>
       *
       * <pre>
       * 业务ID，唯一
       * </pre>
       */
      public Builder clearBusinessID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        businessID_ = getDefaultInstance().getBusinessID();
        onChanged();
        return this;
      }

      // optional int32 messageID = 4;
      private int messageID_ ;
      /**
       * <code>optional int32 messageID = 4;</code>
       *
       * <pre>
       * 消息ID，同一businessID内唯一
       * </pre>
       */
      public boolean hasMessageID() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 messageID = 4;</code>
       *
       * <pre>
       * 消息ID，同一businessID内唯一
       * </pre>
       */
      public int getMessageID() {
        return messageID_;
      }
      /**
       * <code>optional int32 messageID = 4;</code>
       *
       * <pre>
       * 消息ID，同一businessID内唯一
       * </pre>
       */
      public Builder setMessageID(int value) {
        bitField0_ |= 0x00000008;
        messageID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageID = 4;</code>
       *
       * <pre>
       * 消息ID，同一businessID内唯一
       * </pre>
       */
      public Builder clearMessageID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageID_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 5;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * 发送者名字
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * 发送者名字
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * 发送者名字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * 发送者名字
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * 发送者名字
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * 发送者名字
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }

      // optional bytes content = 6;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 6;</code>
       *
       * <pre>
       * 协议内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes content = 6;</code>
       *
       * <pre>
       * 协议内容
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 6;</code>
       *
       * <pre>
       * 协议内容
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 6;</code>
       *
       * <pre>
       * 协议内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // optional string responseAddress = 7;
      private java.lang.Object responseAddress_ = "";
      /**
       * <code>optional string responseAddress = 7;</code>
       *
       * <pre>
       * 回复地址，仅在REQUEST中包含
       * </pre>
       */
      public boolean hasResponseAddress() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string responseAddress = 7;</code>
       *
       * <pre>
       * 回复地址，仅在REQUEST中包含
       * </pre>
       */
      public java.lang.String getResponseAddress() {
        java.lang.Object ref = responseAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          responseAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string responseAddress = 7;</code>
       *
       * <pre>
       * 回复地址，仅在REQUEST中包含
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResponseAddressBytes() {
        java.lang.Object ref = responseAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string responseAddress = 7;</code>
       *
       * <pre>
       * 回复地址，仅在REQUEST中包含
       * </pre>
       */
      public Builder setResponseAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        responseAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseAddress = 7;</code>
       *
       * <pre>
       * 回复地址，仅在REQUEST中包含
       * </pre>
       */
      public Builder clearResponseAddress() {
        bitField0_ = (bitField0_ & ~0x00000040);
        responseAddress_ = getDefaultInstance().getResponseAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseAddress = 7;</code>
       *
       * <pre>
       * 回复地址，仅在REQUEST中包含
       * </pre>
       */
      public Builder setResponseAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        responseAddress_ = value;
        onChanged();
        return this;
      }

      // optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;
      private com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result result_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.Builder, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.ResultOrBuilder> resultBuilder_;
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      public Builder setResult(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      public Builder setResult(
          com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      public Builder mergeResult(com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              result_ != com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.getDefaultInstance()) {
            result_ =
              com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.Builder getResultBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      public com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.ResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>optional .com.raycom.comm.proto.service.ServiceCommunicateMsg.Result result = 8;</code>
       *
       * <pre>
       * 回复结果，仅在RESPONSE中包含
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.Builder, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.ResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.Result.Builder, com.raycom.comm.proto.service.ServiceCommunicate.ServiceCommunicateMsg.ResultOrBuilder>(
                  result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.raycom.comm.proto.service.ServiceCommunicateMsg)
    }

    static {
      defaultInstance = new ServiceCommunicateMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.raycom.comm.proto.service.ServiceCommunicateMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ServiceCommunicate.proto\022\035com.raycom.c" +
      "omm.proto.service\"\242\005\n\025ServiceCommunicate" +
      "Msg\022\022\n\007version\030\001 \001(\005:\0012\022U\n\013messageType\030\002" +
      " \001(\0162@.com.raycom.comm.proto.service.Ser" +
      "viceCommunicateMsg.MessageType\022\022\n\nbusine" +
      "ssID\030\003 \001(\014\022\021\n\tmessageID\030\004 \001(\005\022\014\n\004name\030\005 " +
      "\001(\t\022\017\n\007content\030\006 \001(\014\022\027\n\017responseAddress\030" +
      "\007 \001(\t\022K\n\006result\030\010 \001(\0132;.com.raycom.comm." +
      "proto.service.ServiceCommunicateMsg.Resu" +
      "lt\032\267\001\n\006Result\022Z\n\nresultCode\030\001 \001(\0162F.com.",
      "raycom.comm.proto.service.ServiceCommuni" +
      "cateMsg.Result.ResultCode\022\024\n\014errorCommen" +
      "t\030\002 \001(\t\";\n\nResultCode\022\013\n\007SUCCESS\020\000\022\010\n\004FA" +
      "IL\020\001\022\026\n\022SYSTEM_INNER_ERROR\020\002\"\267\001\n\013Message" +
      "Type\022\013\n\007REQUEST\020\000\022\014\n\010RESPONSE\020\001\022\022\n\016SUBMI" +
      "T_REQUEST\020\002\022\023\n\017SUBMIT_RESPONSE\020\003\022\023\n\017CONF" +
      "IRM_REQUEST\020\004\022\024\n\020CONFIRM_RESPONSE\020\005\022\022\n\016C" +
      "ANCEL_REQUEST\020\006\022\023\n\017CANCEL_RESPONSE\020\007\022\020\n\014" +
      "NOTIFICATION\020\010B3\n\035com.raycom.comm.proto." +
      "serviceB\022ServiceCommunicate"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_descriptor,
              new java.lang.String[] { "Version", "MessageType", "BusinessID", "MessageID", "Name", "Content", "ResponseAddress", "Result", });
          internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_descriptor =
            internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_descriptor.getNestedTypes().get(0);
          internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_raycom_comm_proto_service_ServiceCommunicateMsg_Result_descriptor,
              new java.lang.String[] { "ResultCode", "ErrorComment", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
